solokeys/solo1

- .travis.yml
- Makefile
Before you merge this enable Travis as a github app (A SoloKeysSec admin should add it via the Marketplace in the top bar).  Then merge this and it will do a build-smoke-test in CI, failing if the build fails.  I figured that was enough of a test for now.
> Add travis-ci support and better test build

- targets/stm32l442/src/flash.c
I run cppcheck :)
Shifting *signed* 32-bit value by 31 bits is undefined behaviour.
> Fix undefined behavior

- pc/device.c
udp_server() is being called second time during the simulated run, which
fails due to trying to claim already used port. This patch adds cache to
the udp_server() result.
Example failing run:
```
$ ./main 
state file exists                                 
bind failed: Address already in use               
```
With patch the simulation starts as expected. The direct cause is probably in calling the `device_init()` more than one time - perhaps an issue worth to investigate further?
Environment: 
- Fedora 29
- g++ (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
Edit: all tests pass
> Avoid 2nd start of the simulation server

- docs/solo/udev.md
The `vendorId` and `productId` of `Solo` were assigned to `U2F Zero` and vice versa.
> Fix udev documentation

- fido2/ctap.c
- fido2/ctap.h
Take into account leading zeroes in the size to copy, for both R and S
ingredients of the signature.
Issue was occuring only in cases, when there was a leading zero for the
S part.
Refactor ctap_encode_der_sig():
- add in_ and out_ prefixes to the function arguments
- mark pointers const
- clear out buffer
Tested via simulated device on:
- Fedora 29
- gcc (GCC) 8.2.1 20181215 (Red Hat 8.2.1-6)
- libasan 8.2.1 / 6.fc29
(same machine, as in the related issue description)
by running ctap_test() Python test in a loop for 20 minutes (dev's
counter 400k+). Earlier issue was occuring in first minutes.
Tested on Nucleo32 board, by running the ctap_test() 20 times.
Fixes https://github.com/solokeys/solo/issues/94
> Fix buffer overread in ctap_encode_der_sig()

- .gitignore
- Dockerfile
- Makefile
- README.md
- docker-build.sh
- tools/requirements.txt
A first step towards reproducible builds, answers https://github.com/solokeys/solo/issues/59 and Linux side of https://github.com/solokeys/solo/issues/19.
"It works on my machine", which is Linux.
Next steps towards reproducibility:
- lock down inputs
- (...[many fiddly details](https://reproducible-builds.org/docs/)...)
- sign builds (with some designated Solo Hacker attestation key)
We could start by adding a cronjob to Travis, to copy nightly builds generated by this PR's Dockerfile to [Bintray](https://bintray.com/solokeys), or as GitHub releases (I think this approach requires [a dance with force-updating tags](https://github.community/t5/How-to-use-Git-and-GitHub/Nightly-Builds-Latest-Branch-Releases/m-p/5000#M1621)).
> Docker build

- tools/ctap_test.py
- updated attestation verification to work with latest version of fido2-python library 
- added option to use `forceUDPBackend` from `solo-python` to test with simulated Solo
```
python ctap_test.py sim  # Use UDP
```
> Testing improvements

- .gitmodules
- Makefile
- fido2/crypto.h
- fido2/ctaphid.c
- fido2/ctaphid.h
- targets/stm32l432/Makefile
- targets/stm32l432/build/application.mk
- targets/stm32l432/build/bootloader.mk
- targets/stm32l432/src/crypto.c
This pull request adds support for SHA512, and implicitly introduces a dependency on [cifra](https://github.com/ctz/cifra), which I forked as https://github.com/solokeys/cifra in case the original ever goes away.
The sibling commit https://github.com/nickray/solo-python/commit/f263e8fa2f5910dbeade3a674c6098d7202fe593 proves that the hash works:
```
% dd if=/dev/urandom bs=1 count=7609 of=max_ctaphid_size &>/dev/null
% sha512sum max_ctaphid_size
75ad15fe7235ac223f4e056e53bd6db7a29c3031be92a9079bfacea0208029c9642e8d6855d96615443bf0b9c4eb434638a437c90f51db771cf2671042dce960  max_ctaphid_size
% solo key sha512sum max_ctaphid_size
75ad15fe7235ac223f4e056e53bd6db7a29c3031be92a9079bfacea0208029c9642e8d6855d96615443bf0b9c4eb434638a437c90f51db771cf2671042dce960
```
Implementation size added is …
> SHA512 (via Cifra)

- pc/device.c
- tools/ctap_test.py
- tools/test_sw_token.sh
This adds small modifications to the PC build and adds more testing to the `ctap_test.py` script.  Adding this to CI should be straightforward now.
Many of the tests are already on master. 
To test out, build Solo for PC.
```
cd solo/
make
```
Run a script that runs the Solo binary and restarts it when necessary.
```
./tools/test_sw_token.sh
```
Run tests in "simulation" mode, in another terminal.
```
python ./tools/ctap_test.py sim fido2 rk u2f hid
```
> Testing fido2

- fido2/ctap.c
- fido2/ctap.h
- fido2/ctap_parse.c
- fido2/ctap_parse.h
- targets/stm32l432/build/application.mk
- targets/stm32l432/src/redirect.c
- tools/ctap_test.py
This adds the hmac-secret extension to Solo's CTAP implementation.
I haven't been able to find a service to use it with.  Apparently it's a requirement for Windows 10 log in, but I haven't been able to set up a security key with Windows yet.  
I tested by implementing `hmac-secret` tests in `ctap_test.py fido2-ext`, and making sure those work with Yubikey 5, which has `hmac-secret` implemented.  Then testing `ctap_test.py fido2-ext` works with Solo.
> Hmac-secret

- targets/stm32l432/lib/usbd/usbd_composite.c
- udev/Makefile
- udev/ModemManager-override.conf
Improves https://github.com/solokeys/solo/issues/62, but the drop-in file is a little brittle.
The real solution would be to include our VID/PID pair in ModemManager upstream.
https://bugs.freedesktop.org/show_bug.cgi?id=85007#c4
~~http://cgit.freedesktop.org/ModemManager/ModemManager seems to be down right now though.~~ https://gitlab.freedesktop.org/mobile-broadband/ModemManager/issues/111
> Do not signal "AT modem" for ACM-CDC serial

- targets/stm32l432/src/rng.c
I think `get_rng_bytes` writes one byte too many if `sz` is not a multiple of 4.
> Fix buffer overrun and use correct size for random u32

- fido2/ctap.c
- tools/testing/tests/fido2.py
Changes how pin is enforced for get assertion requests: #151.  Now get assertion requests are allowed with no pin supplied, but the UV bit will be cleared.
> Pin lockout ga

- docs/solo/documenting.md
To avoid this error:
```
[ernie@eahimac2 solo[master*]]$ mkdocs serve
INFO    -  Building documentation...
ERROR   -  Config value: 'markdown_extensions'. Error: Failed loading extension "markdown_include.include".
Aborted with 1 Configuration Errors!
[ernie@eahimac2 solo[master*]]$
```
> include markdown-include mkdocs dependency

- fido2/ctap.c
- fido2/ctap.h
- fido2/ctap_parse.c
- fido2/u2f.c
- fido2/u2f.h
- targets/stm32l432/src/redirect.c
- tools/testing/tests/fido2.py
If a user registers using U2F, and then later authenticates on a browser that only uses FIDO2, it won't work since Solo's CTAP2 and CTAP1 have different key handles/ids, and Solo CTAP2 doesn't attempt to use a CTAP1 key handle.
This update adds support for CTAP1 key handles in CTAP2, so the above scenario will work.  Tests included.  Tested it works by registering with U2F on Chrome, updating key, and then authenticating with FIDO2.
> Fix u2f on fido2

- fido2/main.c
- pc/app.h
- pc/device.c
- tools/gadgetfs/Makefile
There is a HID gadget driver on Linux which provides emulation of USB
HID devices. This could be very useful for testing the Solo firmware
without actual hardware, using only a Linux box.
This patch adds a command line argument which specifies whether the
existing UDP backing should be used or the new one which reads and
writes to /dev/hidg0.
Testing done:
1. Created HID device with configfs
2. Started "./main -b hidg" as root
3. Successfully executed Webauthn registration and authentication on
the same Linux machine
Closes: #122
> Add support for hidg devices on Linux

- fido2/ctap.c
- fido2/ctap.h
- fido2/device.h
- fido2/extensions/wallet.c
- fido2/u2f.c
- pc/device.c
- targets/stm32l432/bootloader/main.c
- targets/stm32l432/build/application.mk
- targets/stm32l432/build/bootloader.mk
- targets/stm32l432/lib/stm32l4xx_hal_tsc.h
- targets/stm32l432/src/ams.c
- targets/stm32l432/src/ams.h
- targets/stm32l432/src/app.h
- targets/stm32l432/src/device.c
- targets/stm32l432/src/init.c
- targets/stm32l432/src/nfc.c
- targets/stm32l432/src/nfc.h
- targets/stm32l432/src/sense.c
- targets/stm32l432/src/sense.h
Adds capacitive touch sensing support to Solo, which is only supported on the soon-to-be released "Somu".  Pulling pin `PB1` to ground enables use of touch sensing instead of button, so the same firmware can be used on all models.
Somu has 2 capacitive touch buttons, which are currently OR'd together and just function as one button.
Tested this works fine on Somu prototype, and Solo USB, and Solo Tap.
> Capacitive touch sensing

- targets/stm32l432/lib/usbd/usbd_hid.c
'USBD_HID_DeInit' is written as 'USBD_HID_Init'; likely a copy-paste
error. This patch should fix it.
> Fix minor typo in comment

- targets/stm32l432/lib/usbd/usbd_hid.c
As demonstrated by @colinoflynn, the memory of Solo can be dumped with fault injection.  A physical glitch is inserted at the right time to cause an effective instruction skip, and cause all of SRAM to get read out for a USB request.
This is a quick fix to limit the user supplied length value to 128 bytes and make it harder to skip with fault injection.
> limit length of wLength

- fido2/crypto.h
- fido2/ctap.c
- targets/stm32l432/src/crypto.c
- tools/testing/tests/fido2.py
- tools/testing/tests/tester.py
- tools/testing/tests/u2f.py
The length of authdata wasn't passed correctly and did not catch the extension data like for `hmac-secret` (#228).
> Fix hmac secret

- fido2/ctap.c
- tools/testing/tests/fido2.py
A few small fixes made with the help of @aseigler.  Now Solo is tested to work fine with Windows Hello.
* Change error code returned for PIN status
* Change how CTAPHID_STATUS was handled prior to user presence.
> Windows hello response codes

- docs/solo/nucleo32-board.md
- mkdocs.yml
Provide description about running and testing Solo firmware on the [STM32 Nucleo] board.
Please review. Perhaps the place to link it is in `building.md`, rather than in a global menu.
[STM32 Nucleo]: https://www.st.com/en/evaluation-tools/stm32-mcu-nucleo.html?querycriteria=productId=LN1847
> Describe running Solo on the Nucleo board

- targets/stm32l432/build/common.mk
- targets/stm32l432/lib/stm32l4xx_ll_exti.c
- targets/stm32l432/lib/stm32l4xx_ll_exti.h
- targets/stm32l432/src/device.c
- targets/stm32l432/src/init.c
Previously, Solo would only block a U2F request for about 750 milliseconds, and it's on the platform to poll repeatedly.  If the platform has a bit of a long delay between polls, this can make an annoying window you have to activate the button in.
This should solve the issue by "caching" the button press for 2 seconds.  If the last button press was within the last 2 seconds, then this counts as 1 user presence check.
> cache button press for 2s

- fido2/ctap.c
- fido2/ctap.h
- fido2/ctap_errors.h
Previously fido2 requests would wait 5s before failing, which is too short.  Increase to 29s.
After [29s] timeout, `CTAP2_ERR_ACTION_TIMEOUT` is returned, which is different than before.
Simplify handling of user presence in other areas
> refactor fido2 user presence handling & increase timeout to 29s

- targets/stm32l432/src/device.c
> make touch sensor edge based to avoid approving >1 transaction

- fido2/apdu.c
- fido2/apdu.h
- targets/stm32l432/src/nfc.c
Specifically return SW_WRONG_LENGTH when there is incorrect length.  With this, Solo NFC passes all FIDO Alliance conformance tests.
> return SW_WRONG_LENGTH for incorrect lc

- fido2/ctap.c
- fido2/u2f.c
- fido2/u2f.h
- pc/device.c
Previously, FIDO2 credentials will not work for U2F for Solo.  This adds support to U2F for FIDO2 registered credential IDs.
> Fido2 on u2f

- docs/solo/application-ideas.md
- mkdocs.yml
Hello,
I added a new section with ideas around Solo.
Please review and give me feedback.
> Document application ideas

- targets/stm32l432/Makefile
- targets/stm32l432/build/bootloader.mk
Currently the `Makefile` script expects `arm-none-eabi-size` to be in the PATH.
The docker container does not have it.
`$(SZ)` is alias that already exist with proper path. 
So `$(SZ)` should be used instead of  `arm-none-eabi-size`.
> Fix docker build

- .gitignore
- .travis.yml
- Dockerfile
- Makefile
- README.md
- in-docker-build.sh
- targets/stm32l432/Makefile
- targets/stm32l432/build/bootloader.mk
- targets/stm32l432/build/common.mk
This PR include:
- Fix for docker built. The current docker build process is broken (see #329).
- Add tests for the docker build (so breaking changes will not go unnoticed again).
- Separate building the toolchain and building the firmware. Currently the flow with docker is a little messy. `Dockerfile` installs everything except the `solo-python`. At the same time checkout again the code inside the container. So in order to build the firmware we have to push the code to `origin`. This PR uses Docker to build a toolchain container  that can build the firmware but use the code on the local machine. This is done mapping the main repo inside `/solo` in the container. `make docker-build-toolchain` builds the toolchain and `make docker-build-all` builds all the different type of the firmware.
- …
> Split docker makefile in toolchain build and firmware build

- Makefile
Using the current user id and group removes the need to use `sudo` when
cleaning up build artifacts from the docker build stage.
Issue: #355
`builds/` Directory:
```
total 1820
drwxr-xr-x  2 jnaulty jnaulty   4096 Jan  6 01:57 ./
drwxr-xr-x 13 jnaulty jnaulty   4096 Jan  6 01:52 ../
-rw-r--r--  1 jnaulty jnaulty  44300 Jan  6 01:57 bootloader-nonverifying-3.0.1-2-gf74a77d.hex
-rw-r--r--  1 jnaulty jnaulty    111 Jan  6 01:57 bootloader-nonverifying-3.0.1-2-gf74a77d.sha2
-rw-r--r--  1 jnaulty jnaulty  57633 Jan  6 01:57 bootloader-verifying-3.0.1-2-gf74a77d.hex
-rw-r--r--  1 jnaulty jnaulty    108 Jan  6 01:57 bootloader-verifying-3.0.1-2-gf74a77d.sha2
-rw-r--r--  1 jnaulty jnaulty 221762 Jan  6 01:57 bundle-hacker-3.0.1-2-gf74a77d.hex
-rw-r--r--  1 jnaulty jnaulty    101 Jan  6 01:57 …
```
> Use current user at build container runtime

- targets/stm32l432/bootloader/bootloader.c
Fix an issue in Solo bootloader where the version check can be bypassed, allowing earlier firmware versions to be programmed on secure models.  The fix is to enforce writes on ascending addresses.
> enforce ascending writes in bootloader update

- docs/solo/customization.md
This is just a minor fix for actually using the previously defined `CN=example.com` in the certification information.
> Fix certification information

- fido2/ctaphid.c
- targets/stm32l432/bootloader/bootloader.c
- targets/stm32l432/src/device.c
- targets/stm32l432/src/init.c
Fixes another issue that could lead to a version bypass as pointed out by @fcremo [here](https://github.com/solokeys/solo/pull/368#issuecomment-584042556).
Additionally, added a command to force flash locking to support users locked out of the official way to secure hacker models.
To force lock flash on your device, install `solo-python` with pip3, and run `python3 -c "import solo ; d = solo.client.find() ; d.send_data_hid(0x99 ^ 0x80,'')"`.
> Fix potential version bypass in bootloader, and add command to lock flash

- fido2/ctap_parse.c
- targets/stm32l432/build/application.mk
Adds more checks to strictly check CBOR and, more importantly, limits recursion in tinycbor to a safe limit.
Based on [security audit by DoyenSec](https://blog.doyensec.com/2020/02/19/solokeys-audit.html).
> Cbor safety

- fido2/ctap.c
- fido2/ctap.h
- fido2/ctap_parse.c
- fido2/ctap_parse.h
- fido2/log.c
- fido2/log.h
Implement command 0x41 which is used by OpenSSH for reading RKs. It has
the following subcommands:
* CMD_CRED_METADATA - get number of saved/remaining RKs
* CMD_RP_BEGIN/CMD_RP_NEXT - iterate over the saved RPs
* CMD_RK_BEGIN/CMD_RK_NEXT - iterate over the RKs for a given RP
This fixes issue #374
> Implement commands for management of resident keys

- fido2/ctap.c
The check_retr macro is evaluating its argument twice, so when we do:
check_retr( ctap2_user_presence_test(...) )
the user presence function is called twice and the user has to press the
button twice. This is regression introduced with commit 3b53537.
> Fix user presence test when pinAuth is empty

- fido2/ctap.c
- fido2/ctap.h
> Do not return NO_CREDENTIALS if there are no RKs and meta is requested

- fido2/ctap.c
- fido2/ctap_parse.c
* Fixes clients that enumerate DFS (Chrome tool)
* Fixed some potential issues for enumerating RP's
> Allow depth first search when enumerating credentials

- docs/solo/programming.md
Based on the discussion at #427 a change to explicitly call in the docs that a DFU update erases everything that already exists in the solokey flash memory. For the sake of newcomers.
> Explicitly call that a DFU update erases everything.

- docs/tutorial-getting-started.md
- docs/tutorial-writing-extensions.md
- mkdocs.yml
Added two tutorials to the docs:
- **Getting started**: Introductionary tutorial to changing code for the maker
- **Writing an extension**: Tutorial for writing a CTAP extension. Exchange of ping pong messages was chosen as an example.
When I started to get a feeling for the code, I wrote some notes for myself as a tutorial. It is oriented at the example of changing the LED color already mentioned in the documentary. When I started, I would have liked a step-by-step guide to get me started fast.
As I wrote an extension for another project, I decided to also write a tutorial for that as I saw it was mentioned in #5 .
I hope, that these tutorials could help. 
If you spot any errors or find something else, I would appreciate any feedback.
#5
> Add tutorials (getting started, write an extension)

- Dockerfile
Added the ARM compiler Path variable to the Dockerfile. Thisway the arm-none-eabi-gcc can be called from withing the solo make file. Furthermore enables the user to use the ARM compiler without knowing the PATH.
> Added ARM compiler Path to Dockerfile

- .gitmodules
- .travis.yml
- Dockerfile
- Makefile
- fido2/cose_key.h
- fido2/crypto.c
- fido2/crypto.h
- fido2/ctap.c
- fido2/ctap.h
- fido2/ctap_parse.c
- in-docker-build.sh
- targets/stm32l432/Makefile
- targets/stm32l432/build/application.mk
- targets/stm32l432/build/bootloader.mk
For now:
- libsodium(-dev) is expected to be preinstalled on build system for PC
build
- salty needs to be prebuilt and installed into targets/stm32l432/salty/
manually
They key type is stored in the 'masked metadata' area of the key ID.
The auth buffers have been enlarged by 32 bytes to be able to append the client hash before ED25519 signature generation instead of creating a full message copy.
I have tested this successfully using fido2-tools and ssh-keygen/ssh on both PC and Solo Hacker.
All feedback much appreciated!
> POC: add ed25519 support based on libsodium (PC) or salty (solo).

- fido2/device.c
- fido2/version.h
I tried to build the code as standalone application running following commands as stated in the README.md:
```bash
git clone --recurse-submodules https://github.com/solokeys/solo
cd solo
make all
```
this resulted in the following errors:
```bash
/solo/fido2/version.h:36: multiple definition of 'firmware_version'; fido2/libsolo.a(ctaphid.o):/solo/fido2/version.h:36: first defined here
/solo/fido2/device.c:29: multiple definition of 'RK_STORE'; pc/device.o:/solo/pc/device.c:31: first defined here
```
This pull requests fixes this issue.
> fix make all target

- Makefile
- declare firmware_version extern in fido2/version.h
- declare RK_STORE 'weak' in fido2/device.c, like the functions
operating on it
Tested on Ubuntu 20.10 using gcc-9 and gcc-10.
> PC: make build using gcc 10 work.

- fido2/ctap.c
This change fixes some issues with the [fido2-tests](https://github.com/solokeys/fido2-tests). Specifically it fixes:
- [This line](https://github.com/solokeys/fido2-tests/blob/9561b5b50279c2e71db37aedd241b029627b38b1/tests/standard/fido2/test_resident_key.py#L221). Now Solo returns the correct number of credentials allowing one more test to succeed.
- [These lines](https://github.com/solokeys/fido2-tests/blob/9561b5b50279c2e71db37aedd241b029627b38b1/tests/standard/fido2/test_resident_key.py#L238-L240) since `getAssertionState.user_verified` is no longer mistakenly set to 0 due to a wrong size used during the memmove().
- [These lines](https://github.com/solokeys/fido2-tests/blob/9561b5b50279c2e71db37aedd241b029627b38b1/tests/standard/fido2/test_resident_key.py#L170-L172) for same reason …
> Fixing counter increment in ctap_filter_invalid_credentials()

- fido2/ctap.c
I wondered that the for loop works without brackets, when more than one statement is executed. Maybe it works with if-else statement.
So I added the brackets for better understanding.
> added brackets to for loop, because of more than single line statement

- fido2/ctap.c
This fixes incorrect cbor ordering reported in #502, #499.
> Fix incorrect cbor ordering

- SECURITY.md
- docs/programming.md
- docs/tutorial-getting-started.md
Hello, this PR will remove the obsolete `--hacker|--secure` arguments from `solo key update` and some unneeded commands since the latest solo python version makes sure the key is in bootloader mode. Also, fixes some typos.
> docs: Remove obsolete flags from solo key update

- fido2/ctap_parse.c
- pc/device.c
The call to `nanosleep` was missing it's header and the `length` calculation in `parse_cred_mgmt_subcommandparams` could be wrong when compiled for 64-bit targets. Both of these showed up as compiler warnings.
I'm no C developer, but I believe these changes are correct fixes.
Edit: These were the only warnings that showed up when running `make all` on Fedora 33.
> Fix compilation warnings

- fido2/ctap.c
- fido2/ctap_parse.c
Fixes an issue where user ID is not added in the response of getAssertion when the associated credential is a resident key.
> compare only credId when comparing rk creds to allowList

- docs/udev.md
I just received my solokey V2, plugged it into my machine running Debian 11 (bullseye), and i successfully was able to set it up with google, github... 
I'm using:
Mozilla Firefox 78.15.0esr
systemd 247 (247.3-6)
> works out-of-box on Debian 11

- docs/bootloader-mode.md
Hello,
it took me almost half a day to stop misreading how I activate the bootloader mode with the button method (always plugged in first and _then_ pressed the button). To save the next careless reading person the time, I wanted to point out the order of actions more clearly.
> Documentation: Clarify order of actions for bootloader button method
