- README.md
change `git submodules` to `git submodule`
> Update README.md. Edit typo mistake.

- 99-solo.rules
- docs/solo/udev.md
A couple of corrections regarding Udev rules documentation.
Added an Udev rule to symlink to the serial port.
Work in progress - testing connection to serial to be exact.
> Udev rules related docs update

- .travis.yml
- Makefile
Have travis run cppcheck on the code in this repo (hence the multiple runs)
> add cppcheck to travis

- fido2/apdu.h
- fido2/ctaphid.c
- fido2/main.c
- fido2/u2f.c
- fido2/u2f.h
- targets/stm32l432/Makefile
- targets/stm32l432/src/ams.c
- targets/stm32l432/src/ams.h
- targets/stm32l432/src/app.h
- targets/stm32l432/src/device.c
- targets/stm32l432/src/nfc.c
- targets/stm32l432/src/nfc.h
> DO NOT MERGE! NFC

- targets/stm32l432/src/app.h
- targets/stm32l432/src/device.c
- targets/stm32l432/src/led.c
added led normalization. it looks more cool)
https://en.wikipedia.org/wiki/Weber%E2%80%93Fechner_law
https://en.wikipedia.org/wiki/Stevens%27s_power_law
sorry for russian here(
http://radiolaba.ru/polezno-znat/regulirovka-yarkosti-svetodioda.html
video shows it in easy way
https://www.youtube.com/watch?v=OGk2lNBPmjc
P.S. it just test of my new environment)
> led emission normalization

- .travis.yml
- Makefile
Black was already in the Makefile, I just added a `blackcheck` target that checks but doesn't reformat, and added it to the `test` target it so that it would be called by travis.
> Add black to travis checking

- targets/stm32l432/bootloader/bootloader.c
> fix bootloader versions

- Dockerfile
- Makefile
- in-docker-build.sh
Preparing for a `solo key update --hacker --bundle` that updates both bootloader and firmware.
> Build bundle-hacker-${version}.{hex,sha2}

- targets/stm32l432/bootloader/main.c
@conorpp can you check. We should avoid all and any warnings in the build process.
> I think this does it

- tools/ctap_test.py
Not sure how, but my previous refactoring and some extra tests in `ctap_test.py` got over-written with an older version.  This copies what should be the latest version and re-applies a fix to comment in #142.  rip commit history :(
> Testing refactor

- docs/solo/fido2-impl.md
Spelling, grammar (consistent tense, extra "allows" word)
> Docs fixups

- docs/solo/building.md
just cleaning up some typos I noticed going through the docs as a first-timer
> More docs fixups

- fido2/ctap.c
- targets/stm32l432/build/application.mk
- targets/stm32l432/src/device.c
- targets/stm32l432/src/nfc.c
Fix some small issues with NFC operation.
* U2F in NFC was expecting a button press. 
* USB peripheral was starting when powered by NFC.  #174
> Nfc adjustments

- fido2/ctap.c
> use persisted key info

- tools/testing/main.py
- tools/testing/tests/fido2.py
- tools/testing/tests/tester.py
> Nfc testing

- docs/solo/nucleo32-board.md
Improving and updating documentation of nucleo32 for current version.
> Added OsX arm install, updated FIDO2 test site links

- docs/solo/bootloader-mode.md
- docs/solo/building.md
- docs/solo/customization.md
- docs/solo/programming.md
- docs/solo/solo-extras.md
- in-docker-build.sh
- mkdocs.yml
- targets/stm32l432/Makefile
Improve documentation on building and programming.  Made it more clear the distinctions of DFU vs bootloader.
Added page for customization for making a custom attestation certification.
Added page for RNG use.
> Documentation improvements

- docs/solo/udev.md
libu2f-host 1.1.10 and systemd developments
> Update udev docs

- fido2/crypto.c
- fido2/crypto.h
- fido2/ctap.c
- pc/device.c
- targets/stm32l432/src/crypto.c
- targets/stm32l432/src/nfc.c
Small fixes needed for all tests to pass all standard tests from https://github.com/solokeys/fido2-tests
> Nfc fido2 fixes

- fido2/apdu.h
- targets/stm32l432/src/nfc.c
as in iso 14443.
fix bug with HID omnikey readers
> add output chaining with GET RESPONSE command 

- fido2/apdu.h
- fido2/device.h
- pc/device.c
- targets/stm32l432/src/nfc.c
> solo reset command

- targets/stm32l432/src/nfc.c
- targets/stm32l432/src/nfc.h
add checking some rare case in iso14443-4 chaining. add NAK checking and aborting the data sending.
> NAK check in chaining

- docs/solo/udev.md
not everyone has a github account, wants one or wants to setup ssh keys.
> clone using https instead

- targets/stm32l432/src/ams.c
- targets/stm32l432/src/ams.h
- targets/stm32l432/src/crypto.c
- targets/stm32l432/src/device.c
- targets/stm32l432/src/flash.c
- targets/stm32l432/src/init.c
- targets/stm32l432/src/init.h
- targets/stm32l432/src/main.c
- targets/stm32l432/src/nfc.c
- targets/stm32l432/src/nfc.h
- targets/stm32l432/src/sense.c
- targets/stm32l432/src/sense.h
Hi,
I just did some code cosmetics. I added void statement to function prototypes if parameter is empty.
Also I added some linefeed for better readability of functions.
It's my first time working on an open source project, so I'm open for all input from you. Hope I did this pull request right.
Thanks
> Code cosmetics

- Makefile
- fido2/ctap.c
- fido2/ctap.h
- fido2/ctaphid.c
- fido2/ctaphid.h
- fido2/device.h
- pc/device.c
- targets/stm32l432/src/device.c
Experimental feature enabled on hacker build to allow key backups.
> Key backup

- Dockerfile
- Makefile
- docs/solo/bootloader-mode.md
- docs/solo/building.md
- docs/solo/customization.md
- docs/solo/programming.md
- fido2/ctaphid.c
- in-docker-build.sh
- targets/stm32l432/Makefile
- targets/stm32l432/bootloader/bootloader.h
- targets/stm32l432/src/device.c
- targets/stm32l432/src/flash.c
Changes to build to take advantage of simplified firmware (from hacker/secure) introduced in #331
> Simplify build

- docs/solo/application-ideas.md
Added Manjaro setup for passwordless and second factor login to
documentation of applcation ideas. Also did some text formating.
> Added how to setup Manjaro 18.x. for passwordless and second factor login

- README.md
I described basic steps how to apply updates.
> Introduction update manual

- fido2/ctap.c
- fido2/ctap.h
- fido2/ctap_parse.c
- fido2/ctaphid.c
- fido2/ctaphid.h
- fido2/device.c
- fido2/device.h
- fido2/u2f.c
- pc/device.c
- targets/stm32l432/linker/stm32l4xx.ld
- targets/stm32l432/src/device.c
Cred protect extension for Microsoft Azure AD
> Credprotect

- fido2/ctap.c
Fixes issue found by @My1: https://github.com/solokeys/solo/issues/407
> dont return index >= ctap_rk_size()

- docs/solo/udev.md
Arch Linux has out of the box for Solo and a dedicated wiki page which I have linked.
Also fixed an incorrect systemd command.
> Update documentation for Arch Linux

- docs/application-ideas.md
Hi @nickray 
I have completed the luks encryption tool which uses solokey for full disk encryption.
https://github.com/saravanan30erd/solokey-full-disk-encryption
Currently it supports only Arch Linux, but planning to support other distros in future.
https://github.com/saravanan30erd/solokey-full-disk-encryption/issues/1
Thanks
> update about LUKS in docs

- docs/udev.md
See commit message (and sid package description) for details
> docs/udev: fix pre-udev-244 Debian and Ubuntu package links

- docs/building.md
> Fix typo in building.md
